# Generated by Django 3.2.6 on 2021-08-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
